name: AllAPILoader
main: TheNewHEROBRINE\AllAPILoader\Main
version: 1.0.0
api: 3.0.0-ALPHA7
author: TheNewHEROBRINE
description: Makes the server load every plugin regardless of the API version
load: STARTUP
softdepend: ["DevTools", "FolderPluginLoader"]